version: "2"
services:
  node:
    image: "node:carbon"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - 8000
    ports:
      - 8000:8000
    command: "npm run start:docker"
    links:
    - mongo
  mongo:
    image: mongo:3.4
    expose:
    - 27017
    ports:
    - 27018:27017
    volumes:
      - ./.data/db:/data/db
      - ./data:/examples